stages:
  - scan
  - notify
job_scan:
  stage: scan
  script:
    - sonar-scanner -Dsonar.projectKey="${CI_PROJECT_NAMESPACE}_${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}" -Dsonar.sources=.
  only:
  - branches
notify_job:
  stage: notify
  script:
    - echo "Notifying external service..."
    - |
      curl -X POST https://portal.ssdevops.com/admin-api/ssdevops/gitlab/runner/ci \
        -H "Content-Type: application/json" \
        -d '{
              "projectId": "'$CI_PROJECT_ID'",
              "branchName": "'$CI_COMMIT_REF_NAME'",
              "username": "'$GITLAB_USER_LOGIN'",
              "projectKey": "'${CI_PROJECT_NAMESPACE}_${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}'"
            }'
  only:
    - branches
